### ISSUE TITLE
Join VueJS Ukrainian translation

### ISSUE THREAD

**Issue by ValeriiMal** [vuejsorgua/ua.vuejs.org#2]
Hello!

I'd like to translate some content in the documentation. What I can start with and how?

**Comment by matrunchyk** [comment]
Hello! 
Thanks for joining and welcome! 

Would you want to start with [computed](https://github.com/matrunchyk/ua.vuejs.org/blob/master/src/v2/guide/computed.md) and [class and style](https://github.com/matrunchyk/ua.vuejs.org/blob/master/src/v2/guide/class-and-style.md)?

**Comment by ValeriiMal** [comment]
Yeap
Lets start with (computed)[https://github.com/matrunchyk/ua.vuejs.org/blob/master/src/v2/guide/computed.md]

**Comment by kromol** [comment]
Hi guys, is it still live? I'd like to help with translation. What is the process? Just pick any opened issue?

**Comment by matrunchyk** [comment]
@kromol Hey I'm happy you are willing to join us!! ❤️ 

Yes, it is, but due to a lack of participants, it's moving slowly.

Feel free to take one (or two 😄 ) of these:
https://github.com/vuejsorgua/vue2-docs/issues/17
https://github.com/vuejsorgua/vue2-docs/issues/15

I'd recommend using the same vocabulary which is already used. If something you think doesn't have the best translation, let us know, please open an issue so we could attach a relevant PR and tackle it in all the places.
